"""add name description to alert_rules

Revision ID: 0ef3ae2caf84
Revises: df02f2142175
Create Date: 2026-01-07 20:58:49.513369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef3ae2caf84'
down_revision: Union[str, None] = 'df02f2142175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('alert_rules', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'description')
    op.drop_column('alert_rules', 'name')
    # ### end Alembic commands ###
